version: '3.3'
services:
    db:
        image: postgres:12.2
        container_name: app_db
        restart: always
        environment:
            POSTGRES_USER: 'dev'
            POSTGRES_PASSWORD: 'pass'
        volumes:
            - .\init_db:/docker-entrypoint-initdb.d
    java:
        image: openjdk:11
        container_name: app
        restart: always
        ports:
            - 8080:8080
        tty: true
        depends_on:
            - db
        volumes:
            - .\src:/usr/local/src
